- name: naming control using ansible facts
  hosts: frontend
  become: yes
  tasks:
   - name: Install Nginx if RedHat
     ansible.builtin.dnf:
      name: nginx
      state: present
     when: ansible_os_family == "RedHat"

   - name: Install Nginx if debian 
     ansible.builtin.dnf:
      name: nginx
      state: present
     when: ansible_os_family == "Debian"  

