- name: create data types
  host: frontend
  vars:
   DURATION: 120 # this is number
   COURSE: aws devops course #it is string
   IS_LIVE: true #Boolean
   TOOLS:
   - linux
   - shell
   - absible
   CONCEPTS: 
    CI: JENKINS
    SCRIPTING: shell,python,bash,golang
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: duration is: "{{ DURATION }}", coutrse: "{{ COURSE }}", is live: "{{ IS_LIVE }}", tools are: "{{ TOOLS }}",concepts are: "{{ CONCEPTS }}, scripting: "{{ SCRIPTING }}"


